--- #YAML:1.0
name:               Text-Diff3
version:            0.12
abstract:           three way text comparison and merging.
author:
    - MIZUTANI Tociyuki <tociyuki@gmail.com>
license:            GPL2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::Base:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
